### ISSUE TITLE
integration with cerbo gx

### ISSUE THREAD

**Issue by Apollo0584** [christian1980nrw/Victron-ESS__Shelly-Plug-S__AVM-Fritz-DECT200-210__Spotmarket-Switcher#5]
hello,

did you check https://github.com/tfranssen/dynamic-ess ?

currently testing your script on cerbo Gx with latest VenusOS installed.
API connection for Belgium. awaiting token from provider.
possible to activate via schedule for end-user?

**Comment by christian1980nrw** [comment]
No, i didnt know this projekt. I will check it later, thanks. Can you explain your question? I dont get it. The script is running automatically every full hour after installation, there is no GUI for a End User. For Belgium you need the Entsoe API, please read the notes inside the controller.sh how to get the api key.

**Comment by Apollo0584** [comment]
The api from entsoe is not for Belgium. Request needed via the local entity Elia with a token.

My question was if it could be possible with your script to trad and set some parameters,
using the existing menu in the OS (assigning schedule nr4 for example) and take those values to adjust the script. 
That way the user can set multiple fixed values when scripting runs in the background.

**Comment by christian1980nrw** [comment]
Are you sure? Prices from belgium are shown there.
![grafik](https://user-images.githubusercontent.com/6513794/224553946-e1afb2d5-f122-4607-a023-b61c19d5c1d5.png)
If you need other data sources you have to tell me how to get free access to them so that i can have a look.
