### ISSUE TITLE
Feature Request: Nachladen des Akku bis Ziel-SoC wenn die erwartete Solar Energie zu gering dafür ist und dafür die günstigsten Stunden finden

### ISSUE THREAD

**Issue by mpolak77** [christian1980nrw/Victron-ESS__Shelly-Plug-S__AVM-Fritz-DECT200-210__Spotmarket-Switcher#6]
Hi, tolles Skript was du da gemacht hast - ich würde es gerne für Awattar verwenden.

Ich fände auch folgendes Feature nützlich (vielleicht kann dein Skript das ja schon, und ich habe es noch nicht verstanden).

Ich habe nur ein Balkonkraftwerk mit 880 Wp und einen 7.7KWh Speicher dazu .... der wird also nie voll (an den besten Tagen liegt der Brutto-Ertrag bei 5.x KWh). Ich möchte also versuchen den Speicher mit Nachladen zu den billigen Stunden entsprechend zu füllen, dass die teureren Stunden überbrückt werden können .... dabei aber den zur erwartenden Sonnen-Ertrag nicht verschenken. Ich denke, dass das mit einer dynamischen Veränderung des Target-SoC im machbar sein müsste?

in jeder Stunde den Target-SoC so anpassen, dass der zur erwartende PV Ertrag des aktuellen bzw kommenden Tages noch reinpasst ...... und darauf dann die BesteStunde / ZweitbesteStunde / DrittbesteStunde usw Logik noch anwenden.

**Comment by christian1980nrw** [comment]
Hi, dazu müsste man eine Abfrage-Matrix mit Ziel-Ladezustand und erwartetem Solarertrag einbauen.
Momentan fehlt mir die Zeit dazu, aber kann sein das ich sowas nochmal ergänze.
Du kannst momentan in Venus OS aber so viel als Ziel-SOC eintragen was
Du mindestens benötigst um den Tag über mit der Grundlast klarzukommen und den Rest generell für PV reservieren.

Gruß! Christian
